### ISSUE TITLE
Cкрипт установки для Windows не имеет цифровой подписи

### ISSUE THREAD

**Issue by gorbunov-dmitry** [dvfu/fefu_thesis#1]
При запуске сценария установки `install.ps1` возникает следующая ошибка

```
.\install.ps1 : Не удается загрузить файл .\install.ps1. Файл .\install.ps1 не имеет цифровой подписи. Невозможно выполнить сценарий в указанной системе. Для получения дополнительных сведений о выполнении сценариев и настройке политики выполнения см. about_Execution_Policies по адресу https:/go.microsoft.com/fwlink/?LinkID=135170.
строка:1 знак:1
+ .\install.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : Ошибка безопасности: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

На данный момент обойти эту ошибку можно, запустив `PowerShell` от имени администратора и изменив политику безопасности с помощью команды `Set-ExecutionPolicy Unrestricted`.

Возможно, более хорошим решением является добавление цифровой подписи.

**Comment by GoldFeniks** [comment]
По указанной ссылке пишут, что по умолчанию вообще запрещено выполнение всех скриптов, не завивисо от того есть подпись или нет, поэтому менять политику выполнения необходимо в любом случае. Для того, чтобы подписать такой скрипт необходимо регистрировать его в некотором [центре сертификации](https://docs.microsoft.com/ru-ru/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.2#methods-of-signing-scripts), что кажется избыточным в данном случае. Сам скрипт содержит лишь небольшой набор команд, которые можно выполнить и вручную, или подписать скрипт как описано [здесь](https://docs.microsoft.com/ru-ru/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.2#sign-a-script), чтобы его можно было запускать только локально.
